#!/usr/bin/env python

import click
import sys
from disassembler.bytecode_reader import ByteCodeReader, MalformedByteCodeError
from disassembler.ops import disassemble_op


@click.command()
@click.argument("src", nargs=1)
def glacierd_disassemble(src):
    with open(src, "rb") as f:
        bc = f.read()
    reader = ByteCodeReader(bc)
    try:
        while True:
            op = reader.read_op()
            if op is None:
                break
            disassemble_op(reader, op)
    except MalformedByteCodeError as e:
        print("malformed bytecode error: {}".format(e))
        sys.exit(1)


if __name__ == "__main__":
    glacierd_disassemble()
