# Generated by glacierdsl - DO NOT EDIT.

from compiler import bytecode


class StructDef:
    def __init__(self, type_id, member_id):
        self.type_id = type_id
        self.member_id = member_id

    def serialise(self, bc):
        args = list()
        args.append(self.type_id)
        args.append(len(self.member_id))
        args.extend(self.member_id)
        bc.write_op(bytecode.OpCode.STRUCT_DEF, args)


class FunctionDef:
    def __init__(self, function_id, num_args):
        self.function_id = function_id
        self.num_args = num_args

    def serialise(self, bc):
        args = list()
        args.append(self.function_id)
        args.append(self.num_args)
        bc.write_op(bytecode.OpCode.FUNCTION_DEF, args)


class SetVar:
    def __init__(self, variable_id):
        self.variable_id = variable_id

    def serialise(self, bc):
        args = list()
        args.append(self.variable_id)
        bc.write_op(bytecode.OpCode.SET_VAR, args)


class GetVar:
    def __init__(self, variable_id):
        self.variable_id = variable_id

    def serialise(self, bc):
        args = list()
        args.append(self.variable_id)
        bc.write_op(bytecode.OpCode.GET_VAR, args)


class CallFunc:
    def __init__(self, function_id):
        self.function_id = function_id

    def serialise(self, bc):
        args = list()
        args.append(self.function_id)
        bc.write_op(bytecode.OpCode.CALL_FUNC, args)


class Return:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.RETURN, args)


class ReturnVal:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.RETURN_VAL, args)


class Add:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.ADD, args)


class Int:
    def __init__(self, value):
        self.value = value

    def serialise(self, bc):
        args = list()
        args.append(self.value)
        bc.write_op(bytecode.OpCode.INT, args)


class String:
    def __init__(self, bytes):
        self.bytes = bytes

    def serialise(self, bc):
        args = list()
        args.append(len(self.bytes))
        args.extend(self.bytes)
        bc.write_op(bytecode.OpCode.STRING, args)


class Subtract:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.SUBTRACT, args)


class Multiply:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.MULTIPLY, args)


class Divide:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.DIVIDE, args)


class FunctionJmp:
    def __init__(self, function_id, offset):
        self.function_id = function_id
        self.offset = offset

    def serialise(self, bc):
        args = list()
        args.append(self.function_id)
        args.append(self.offset)
        bc.write_op(bytecode.OpCode.FUNCTION_JMP, args)


class HeaderEnd:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.HEADER_END, args)


class Print:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.PRINT, args)


class Eq:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.EQ, args)


class JumpIfTrue:
    def __init__(self, offset):
        self.offset = offset

    def serialise(self, bc):
        args = list()
        args.append(self.offset)
        bc.write_op(bytecode.OpCode.JUMP_IF_TRUE, args)


class JumpIfFalse:
    def __init__(self, offset):
        self.offset = offset

    def serialise(self, bc):
        args = list()
        args.append(self.offset)
        bc.write_op(bytecode.OpCode.JUMP_IF_FALSE, args)


class Jump:
    def __init__(self, offset):
        self.offset = offset

    def serialise(self, bc):
        args = list()
        args.append(self.offset)
        bc.write_op(bytecode.OpCode.JUMP, args)


class Struct:
    def __init__(self, struct_id):
        self.struct_id = struct_id

    def serialise(self, bc):
        args = list()
        args.append(self.struct_id)
        bc.write_op(bytecode.OpCode.STRUCT, args)


class GetStructMember:
    def __init__(self, member_index):
        self.member_index = member_index

    def serialise(self, bc):
        args = list()
        args.append(self.member_index)
        bc.write_op(bytecode.OpCode.GET_STRUCT_MEMBER, args)


class SetStructMember:
    def __init__(self, member_index):
        self.member_index = member_index

    def serialise(self, bc):
        args = list()
        args.append(self.member_index)
        bc.write_op(bytecode.OpCode.SET_STRUCT_MEMBER, args)


class Lt:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.LT, args)


class Vec:
    def __init__(self, size):
        self.size = size

    def serialise(self, bc):
        args = list()
        args.append(self.size)
        bc.write_op(bytecode.OpCode.VEC, args)


class VecAccess:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.VEC_ACCESS, args)


class Map:
    def __init__(self, size):
        self.size = size

    def serialise(self, bc):
        args = list()
        args.append(self.size)
        bc.write_op(bytecode.OpCode.MAP, args)


class MapAccess:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.MAP_ACCESS, args)


class VecPush:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.VEC_PUSH, args)


class VecLen:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.VEC_LEN, args)


class VecPop:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.VEC_POP, args)


class MapInsert:
    def __init__(self):
        pass

    def serialise(self, bc):
        args = list()
        bc.write_op(bytecode.OpCode.MAP_INSERT, args)
